export enum ProjectDetailsPageActions {
  TOGGLE_IS_SELECTED_ALL_JUPYTER = 'ProjectDetailsPageActions/TOGGLE_IS_SELECTED_ALL_LOCAL',
  TOGGLE_IS_SELECTED_ALL_HYDROSHARE = 'ProjectDetailsPageActions/TOGGLE_IS_SELECTED_ALL_HYDROSHARE',
  TOGGLE_IS_SELECTED_ONE_JUPYTER = 'ProjectDetailsPageActions/TOGGLE_IS_SELECTED_ONE_LOCAL',
  TOGGLE_IS_SELECTED_ONE_HYDROSHARE = 'ProjectDetailsPageActions/TOGGLE_IS_SELECTED_ONE_HYDROSHARE',
  SORT_BY_NAME = 'SORT_BY_NAME',
  SEARCH_BY = 'SEARCH_BY',
  SEARCH_PROJECT_BY = 'SEARCH_PROJECT_BY',
}

export enum ProjectsActions {
  SET_PROJECTS = 'SET_PROJECTS',
}
