export enum AppActions {
  VIEW_PROJECT = 'VIEW_PROJECT',
  CLOSE_PROJECT = 'CLOSE_PROJECT',
}

export enum FilterBarActions {
  TOGGLE_SELECT_STATUS_ALL = 'TOGGLE_SELECT_STATUS_ALL',
  TOGGLE_SELECT_STATUS_ONE = 'TOGGLE_SELECT_STATUS_ONE',
  SORT_BY_NAME = 'SORT_BY_NAME',
}

export enum ProjectsActions {
  SET_PROJECTS = 'SET_PROJECTS',
}
